language: python
python:
  - "3.5"
install:
  - pip install python-coveralls
  - pip install coverage
script:  
  - make test 
  - coverage run test_rpn.py
  - coverage report 
after_success:
  - coveralls